Add FAQ and bag-of-tricks
sony/model_optimization pull request #1006
Opened 2024-03-19 16:20 UTC by elad-c

## Pull Request Description:
Add Bag-of-Tricks and FAQ, with links in readme

## Checklist before requesting a review:
- [ ] I set the appropriate labels on the pull request.
- [ ] I have added/updated the release note draft (if necessary).
- [ ] I have updated the documentation to reflect my changes (if necessary).
- [ ] All function and files are well documented. 
- [ ] All function and classes have type hints.
- [ ] There is a licenses in all file.
- [ ] The function and variable names are informative. 
- [ ] I have checked for code duplications.
- [ ] I have added new unittest (if necessary).

2024-03-19 19:19 UTC, ofirgo reviewed
Didn't go over the tricks page itself, but in the meantime, comments on all the rest

2024-03-19 19:19 UTC, ofirgo commented on README.md
> +- [Quantization Bag of Tricks](#quantization-bag-of-tricks)
change to "Quantization Troubleshooting"

2024-03-19 19:19 UTC, ofirgo commented on README.md
> +## Quantization Bag of Tricks
same

2024-03-19 19:19 UTC, ofirgo commented on README.md
> +If the quantization process degrades the model's accuarcy too much, check out the [Bag of Tricks](https://github.com/sony/model_optimization/tree/main/quantization_bag_of_tricks.md)
what is "too much"? I think it needs to be rephrased to something like:
"If the quantized model (suffers from a significant accuracy degradation /  accuracy results are not sufficient)..."

2024-03-19 19:19 UTC, ofirgo commented on README.md
> +for a few "tricks" for improving the quantization.
Remove the "trick" terminology (everywhere).
Change every "bag of tricks" to "quantization troubleshooting" or "quantization accuracy troubleshooting" and here you can maybe change to "few advanced tools and things to look for, for improving the quantized model"

2024-03-19 19:19 UTC, ofirgo commented on README.md
> +Check out the [Frequently Asked Quantions](https://github.com/sony/model_optimization/tree/main/FAQ.md) for common issues.
I think it can be shorten to FAQ here as well

2024-03-19 19:19 UTC, ofirgo commented on model_compression_toolkit/exporter/model_wrapper/keras/builder/fully_quantized_model_builder.py
> +        Logger.info("Please run your accuracy evaluation on the exported model to verify it's accuracy.\n"
exported **quantized** model..

2024-03-19 19:19 UTC, ofirgo commented on model_compression_toolkit/exporter/model_wrapper/keras/builder/fully_quantized_model_builder.py
> +                    "Checkout the FAQ and Bag of Tricks pages for resolving common issues and improving the quantized model accuracy:\n"
same, change bag of tricks

2024-03-19 19:19 UTC, ofirgo commented on model_compression_toolkit/exporter/model_wrapper/pytorch/builder/fully_quantized_model_builder.py
> +        Logger.info("Please run your accuracy evaluation on the exported model to verify it's accuracy.\n"
same comments

2024-03-20 07:41 UTC, ServiAmirPM commented on FAQ.md
I think the difference is whether you want to run on IMX500 or not, no?
so I would add something like:

"**In order for those who seek to run their quantized model on non-IMX500 devices** to truly benefit from quantization..."

or something that makes it clear that this is relevant only for non-IMX500 deployments

2024-03-20 07:43 UTC, ServiAmirPM commented on README.md
Quantization Bag of Tricks (Troubleshoot)
If the quantization process degrades the model's accuarcy **more than expected (up to ~1%)**, check out the [Bag of Tricks](https://github.com/sony/model_optimization/tree/main/quantization_bag_of_tricks.md) for a few "tricks" for improving **the quantization<>accuracy trade-off.**

2024-03-20 07:49 UTC, ServiAmirPM commented on quantization_bag_of_tricks.md
@elad-c you forgot some question marks  in the end of the negative-shift section (right above the Bias correction section):

"Additional care should be taken when using this feature**.????**"

2024-03-20 07:53 UTC, ofirgo commented on FAQ.md
Are you referring to a specific point or the FAQ section in general?
Because the FAQ is not necessarily only for non-IMX500 users.

2024-03-20 07:55 UTC, ServiAmirPM commented on quantization_bag_of_tricks.md
Correction Bias

in the solution - you say "First, .... "
But there's no second... or any continue

2024-03-20 07:57 UTC, ServiAmirPM commented on FAQ.md
Specificly to the point of this FAQ,
It is saying that fake quantize doesn't let you truly benefit from quantization in terms of model size.
It's true only for non-IMX500 usages - isn't it? You run the converter with the fake-quantizatino and it handles it right?

2024-03-20 07:58 UTC, ServiAmirPM commented on quantization_bag_of_tricks.md
You forgot "TODO: Add Exporter stuff" at the end of this file

2024-03-20 08:29 UTC, ofirgo commented on FAQ.md
Yes I think you are correct. You just posted it as a general comment on the top of the FAQ page so I didn't know which point are you referring to.

2024-03-20 09:21 UTC, elad-c commented on README.md
I don't think "tradeoff" is what we aim at here.

2024-03-21 07:43 UTC, ofirgo requested changes

2024-03-21 07:43 UTC, ofirgo commented on quantization_troubleshooting.md
> +## Common Issues
I think that the "common issues" section needs to be removed and split:
- the point regarding concatenation can be a "tip"
- the point regarding torch.fx need to be moved to the FAQ and slightly rephrased (refer to it as "how to handle graph reading errors" or something like that)

2024-03-21 07:43 UTC, ofirgo commented on quantization_troubleshooting.md
> +**Compressing a model with MCT:**
Rephrasing suggestion for the intrduction (yes, I consulted chatgpt it's not totally my phrasing):

**Utilizing MCT for Model Compression:**
The Model Compression Toolkit (MCT) offers numerous functionalities to compress neural networks with minimal accuracy lost. 
However, in some cases, the compressed model may experience a significant decrease in accuracy. 
Fear not, as this lost accuracy can often be reclaimed by adjusting the quantization configuration or setup.

**Restoring Accuracy - Troubleshooting Steps:**
Outlined below are a series of steps aimed at recovering lost accuracy resulting from compression with MCT. 
Some steps may be applicable to your model, while others may not.

2024-03-21 07:43 UTC, ofirgo commented on quantization_troubleshooting.md
> +In this case, the distribution of the target dataset and the representative dataset will not match and accuracy will degrade.
and accuracy will degrade --> which might cause accuracy degradation

2024-03-21 07:43 UTC, ofirgo commented on quantization_troubleshooting.md
> +Increase the number of inputs in the representative dataset, or make sure the inputs are more diverse (e.g. include all the classes, in  a classification model).
inputs --> samples?

2024-03-21 07:43 UTC, ofirgo commented on quantization_troubleshooting.md
> +When implementing quantization on a PyTorch model, MCT's initial step involves converting the model into a graph representation using `torch.fx`.
If here you are writing pytorch as **PyTorch** then make it similar through the entire document

2024-03-21 07:43 UTC, ofirgo commented on quantization_troubleshooting.md
> +## Advanced Quantization Methods
I think that this section needs to come before "debugging tools"

2024-03-21 07:43 UTC, ofirgo commented on quantization_troubleshooting.md
> +
rephrasing suggestion for this paragraph:

In certain instances, even if we've been thorough in following the quantization process, we face challenges like significant accuracy loss in the quantized model or its size surpassing the limitations of our deployment target (e.g., the IMX500). 

To tackle these issues, MCT offers advanced features such as Mixed Precision and GPTQ. 
These functionalities are designed to address accuracy concerns and optimize model size for smoother deployment.

2024-03-21 07:43 UTC, ofirgo commented on quantization_troubleshooting.md
> +In mixed precision quantization, MCT will assign a different number of bit widths to each weight in the model, depending on the weight's layer sensitivity
differsnt number of bit widths --> different bit-width

2024-03-21 07:43 UTC, ofirgo commented on quantization_troubleshooting.md
> +### Mixed Precision Quantization
I don't understand, where did all the mixed precision tips?

2024-03-21 07:43 UTC, ofirgo commented on quantization_troubleshooting.md
> +and a constraint defined by the user, such as target model size.
a resource constraint

2024-03-21 07:43 UTC, ofirgo commented on quantization_troubleshooting.md
> +
General suggestion:
we are referring the users only to our keras tutorials. maybe add a sentence stating (somethinglike):

throughout this document we refer the user for notebooks that demonstrate how to use all the mentioned tools. We refer them to keras notebooks but all tools are also available in pytorch and some of them also have pytorch tutorials. you are welcome to check the complete set of notebooks to get a glimpse of the advanced features of MCT (and put a link)

2024-03-21 07:43 UTC, ofirgo commented on quantization_troubleshooting.md
> +When PTQ (either with or without mixed-precision) fails to deliver the required accuracy, GPTQ is potentially the remedy.
mixed precision either with "-" or without. I usually write without (I saw that in papers) but just be consistent

2024-03-21 07:43 UTC, ofirgo commented on quantization_troubleshooting.md
> +*Note #1*: The finetuning process will take longer to finish than PTQ. As in any finetuning, some hyperparameters optimization may be required.
Much longer (it needs to be clear)

2024-03-21 10:27 UTC, ofirgo approved these changes

2024-03-21 11:20 UTC, Idan-BenAmi commented on FAQ.md
> +# FAQ
I suggest to add table of content and check the subtitle to question form
Why my quantized model has the same size as the original model ?
How to load quantized model?
Why I'm getting "torch.fx" parsing model error?

2024-03-21 11:28 UTC, Idan-BenAmi commented on README.md
> +- [FAQ](#faq)
I suggest to unify this 2 items to 1 section: Troubleshooting.
Where in this section you will refer to the 2 markdown files.

2024-03-21 11:28 UTC, Idan-BenAmi commented on README.md
> +Check out the [FAQ](https://github.com/sony/model_optimization/tree/main/FAQ.md) for common issues.
combine to one section: ## Troubleshooting
Note the the typo: If the accuracy of the quantized model is **too large**

2024-03-21 13:37 UTC, Idan-BenAmi commented on FAQ.md
> +## 1. Why does the size of the quantized model remain the same as the original model size?
Cosmetics:
Add space between the table of contents and the questions.
Minimize the subtitles. it's huge. try ### or ####

2024-03-21 13:39 UTC, Idan-BenAmi commented on README.md
> +Check out the [FAQ](https://github.com/sony/model_optimization/tree/main/FAQ.md) for common issues.
Try this phrasing:
If the quantized model's accuracy drops too much for your application,...

2024-03-21 16:38 UTC, merged