Add metadata quantized models in PTQ & GPTQ facades.
sony/model_optimization pull request #1034
Opened 2024-04-08 08:53 UTC by elad-c

## Pull Request Description:

This PR adds the MCTQ metadata feature to MCT quantized models.
Enabled from the TPC. Added imx500.v2 TPCs that enable metadata.

## Checklist before requesting a review:
- [ ] I set the appropriate labels on the pull request.
- [ ] I have added/updated the release note draft (if necessary).
- [ ] I have updated the documentation to reflect my changes (if necessary).
- [ ] All function and files are well documented. 
- [ ] All function and classes have type hints.
- [ ] There is a licenses in all file.
- [ ] The function and variable names are informative. 
- [ ] I have checked for code duplications.
- [ ] I have added new unittest (if necessary).

2024-04-08 11:40 UTC, ofirgo requested changes

2024-04-08 11:40 UTC, ofirgo commented on model_compression_toolkit/exporter/model_exporter/keras/fakely_quant_keras_exporter.py
> +        # Delete metadata layer is exists
typo (is --> if)

2024-04-08 11:40 UTC, ofirgo commented on model_compression_toolkit/exporter/model_exporter/pytorch/fakely_quant_onnx_pytorch_exporter.py
> +from io import BytesIO
just toverify - is this package already used in MCT? (does it appear in the requirements?)

2024-04-08 11:40 UTC, ofirgo commented on model_compression_toolkit/exporter/model_exporter/pytorch/fakely_quant_onnx_pytorch_exporter.py
> +            onnx_bytes = BytesIO()
can you explain what it does?

2024-04-08 11:40 UTC, ofirgo commented on model_compression_toolkit/target_platform_capabilities/target_platform/targetplatform2framework/target_platform_capabilities.py
> +                 add_metadata: bool = False):
Didn't we say that it should be in the tp model? is there a reason to put it in the tpc?

2024-04-08 11:40 UTC, ofirgo commented on model_compression_toolkit/target_platform_capabilities/target_platform/targetplatform2framework/target_platform_capabilities.py
> +    def versions_dict(self) -> Dict:
I don't understand why is this a TPC method.. is it mandatory to put it here?

2024-04-08 11:40 UTC, ofirgo commented on model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v2/tpc_keras.py
> +
Add a comment, something like "This version enables model metadata saving by default"

2024-04-09 08:12 UTC, reuvenperetz commented on model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v2/tp_model.py
> +
Just making sure: is the metadata the only difference from v1?

2024-04-09 08:12 UTC, reuvenperetz commented on model_compression_toolkit/exporter/model_exporter/pytorch/fakely_quant_onnx_pytorch_exporter.py
> +            onnx_model = add_onnx_metadata(onnx_model, self.model.metadata)  # TODO: get tpc version from tpc
Why the TODO? isn't tpc version already in metadata?

2024-04-09 08:12 UTC, reuvenperetz commented on model_compression_toolkit/exporter/model_exporter/keras/fakely_quant_keras_exporter.py
> +            delattr(self.model, 'metadata_layer')
Maybe add a warning that metadata is not exported in the TFLITE case? (all tflite cases where you delete the metadat_layer)

2024-04-09 16:29 UTC, reuvenperetz approved these changes

2024-04-09 16:50 UTC, ofirgo approved these changes

2024-04-11 12:21 UTC, merged