Add a flag to indicate whether to run mixed precision according to resource utilization provided by user.
sony/model_optimization pull request #1052
Opened 2024-05-01 12:22 UTC by lior-dikstein

## Pull Request Description:

## Checklist before requesting a review:
- [ ] I set the appropriate labels on the pull request.
- [ ] I have added/updated the release note draft (if necessary).
- [ ] I have updated the documentation to reflect my changes (if necessary).
- [ ] All function and files are well documented. 
- [ ] All function and classes have type hints.
- [ ] There is a licenses in all file.
- [ ] The function and variable names are informative. 
- [ ] I have checked for code duplications.
- [ ] I have added new unittest (if necessary).

2024-05-01 14:26 UTC, ofirgo requested changes
Some cosmetic comments.
In addition:
1. Please add a dedicated test for the new feature (define a setup with TPC that would run mixed precision before the new feature, and verify that it didn't run mixed precision). I would replicate this test for each of the available resource utilization types.
2. Please update the release notes draft.
3. Also add a description to the PR with an explanation about the feature (and include it in the commit message when you merge it).

2024-05-01 14:26 UTC, ofirgo commented on tests/keras_tests/feature_networks_tests/feature_networks/weights_mixed_precision_tests.py
> +        assert (quantization_info.mixed_precision_cfg == self.expected_mp_config).all()
I know it's not your original code, but if you already touched it, change the assert to some unitTest assertion

2024-05-01 14:26 UTC, ofirgo commented on tests/pytorch_tests/model_tests/feature_models/mixed_precision_activation_test.py
> +        self.expected_config = [0 for _ in range(8)] + [1]
why the +[1]? maybe add comment cause it's not clear

2024-05-02 08:06 UTC, lior-dikstein commented on model_compression_toolkit/core/common/mixed_precision/resource_utilization_tools/resource_utilization_data.py
> +    Returns: An array of the graph's nodes weights memory in bytes and an array of the graph's
yes

2024-05-02 09:06 UTC, lior-dikstein commented on model_compression_toolkit/core/common/mixed_precision/resource_utilization_tools/resource_utilization_data.py
> +            max_weight_bits = max(weight_n_bit_candidates) if len(weight_n_bit_candidates) > 0 else 0
Refactored the whole function to make it better and more readable

2024-05-02 12:18 UTC, ofirgo requested changes

2024-05-05 13:19 UTC, ofirgo commented on tests/keras_tests/feature_networks_tests/feature_networks/mixed_precision/requires_mixed_precision_test.py
> +import numpy as np
missing license

2024-05-05 13:19 UTC, ofirgo approved these changes

2024-05-06 11:41 UTC, merged