Fix support const as input to linear layers in pytorch
sony/model_optimization pull request #1080
Opened 2024-05-21 13:39 UTC by lapid92

## Pull Request Description:

## Checklist before requesting a review:
- [ ] I set the appropriate labels on the pull request.
- [ ] I have added/updated the release note draft (if necessary).
- [ ] I have updated the documentation to reflect my changes (if necessary).
- [ ] All function and files are well documented. 
- [ ] All function and classes have type hints.
- [ ] There is a licenses in all file.
- [ ] The function and variable names are informative. 
- [ ] I have checked for code duplications.
- [ ] I have added new unittest (if necessary).

2024-05-21 14:26 UTC, elad-c commented on tests/pytorch_tests/model_tests/feature_models/const_representation_test.py
> +                                     'enable_weights_quantization': True,
maybe test with AND without weights quantization?

2024-05-21 19:03 UTC, ofirgo commented
@lapid92 
Please add description to the PR explaining the problem and the solution (and consider including it in the commit message when merging).

2024-05-21 19:14 UTC, ofirgo requested changes

2024-05-21 19:14 UTC, ofirgo commented on model_compression_toolkit/core/common/graph/base_node.py
> +            # Insert only positional weights that are not subject to quantization.
maybe explain why?

2024-05-21 19:14 UTC, ofirgo commented on model_compression_toolkit/core/common/graph/base_node.py
>              assert pos <= len(input_tensors), 'Positional weight index mismatch'
change this to if with a "critical" logger message

2024-05-22 06:34 UTC, ofirgo approved these changes

2024-05-22 06:56 UTC, merged