reshape error fix
sony/model_optimization pull request #1086
Opened 2024-05-26 19:49 UTC by samuel-wj-chapman

## Pull Request Description:
Solution works for all the problem models. However, a cleaner fix might be preferred.

## Checklist before requesting a review:
- [ ] I set the appropriate labels on the pull request.
- [ ] I have added/updated the release note draft (if necessary).
- [ ] I have updated the documentation to reflect my changes (if necessary).
- [ ] All function and files are well documented. 
- [ ] All function and classes have type hints.
- [ ] There is a licenses in all file.
- [ ] The function and variable names are informative. 
- [ ] I have checked for code duplications.
- [ ] I have added new unittest (if necessary).

2024-05-27 05:20 UTC, haihabi commented
@ofirgo please take a look...

2024-05-27 06:50 UTC, ofirgo commented
Hi @samuel-wj-chapman , 
Can you please explain the error and when it occurs?

@elad-c can you please take a look, I think it's related to positional attributes

2024-05-27 08:08 UTC, samuel-wj-chapman commented
error
reshape() takes 2 positional arguments but 5 were given

for the following models
inception_next_small.sail_in1k
inception_next_tiny.sail_in1k
inception_next_base.sail_in1k
inception_next_base.sail_in1k_384

error occurs due to line 161 in [this inception model](https://github.com/huggingface/pytorch-image-models/blob/main/timm/models/inception_next.py)

x = x.mul(self.gamma.reshape(1, -1, 1, 1))

arguments fed through incorrect format. change specifically looks for his case and resolves.

2024-05-27 08:14 UTC, elad-c commented
I think it's the same issue we has with `permute`. We handled it with a [substitution](model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/permute_call_method.py). Maybe we should also handle `reshape` in that substitution.
Anyway, please add a test for this case.

2024-05-27 13:14 UTC, haihabi commented
@elad-c and @samuel-wj-chapman  If we handle this kind of issue via [substitution](https://github.com/sony/model_optimization/pull/model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/permute_call_method.py)., then I suggest that here we take the same approach as well.

2024-05-30 10:06 UTC, Idan-BenAmi commented on model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/reshape_call_method.py
> +    """
typo "permute"

2024-05-30 10:06 UTC, Idan-BenAmi commented on model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/reshape_call_method.py
> +        """
same in here: permute

2024-05-30 11:05 UTC, elad-c requested changes
Can you "reuse" the existing substitution for `permute` and apply it for `reshape` too? Seems to be identical to the permute substitution except for the `NodeMatcher`.
Something like:
```
nodes = NodeOperationMatcher(permute) | NodeOperationMatcher(reshape)
super().__init__(matcher_instance=nodes)
```
would do the trick.

2024-05-30 12:42 UTC, samuel-wj-chapman commented
the pr failed test when i duplicated. the addition line  "if len(node.op_call_args)>1:"  was needed to prevent other correct instances of reshape from being substituted. @elad-c

2024-05-30 12:48 UTC, elad-c commented
Does it fail in the case of permute?

2024-05-30 12:49 UTC, samuel-wj-chapman commented
no :)

2024-05-30 14:10 UTC, elad-c commented on tests/pytorch_tests/model_tests/feature_models/reshape_substitution_test.py
Maybe this file can be avoided. It's very similar to `permute_substitution_test.py`. Can we change it to `transform_fn_call_substitution_test.py` and test both `reshape` and `permute`?

2024-05-30 15:17 UTC, Idan-BenAmi commented on tests/pytorch_tests/model_tests/feature_models/reshape_substitution_test.py
Guessing it's also good to keep the 2 tests.. so we know we check both cases.. but not too critical either way.

2024-05-30 15:21 UTC, samuel-wj-chapman commented on tests/pytorch_tests/model_tests/feature_models/reshape_substitution_test.py
I feel maybe best to keep them separate as we needed to make a change to the original file to allow it to work with both transform types? eg - if isinstance(node.op_call_args[0], (list, tuple)).

2024-06-02 06:11 UTC, elad-c approved these changes

2024-06-03 10:44 UTC, merged