Refactor PyTorch model reader.
sony/model_optimization pull request #1114
Opened 2024-06-19 15:23 UTC by elad-c

## Pull Request Description:
Refactor includes:
1. remove duplication of framework_attr and node.kwargs in FunctionalNodes
2. reorder graph_builders.py
3. fix substitutions following the above changes

## Checklist before requesting a review:
- [ ] I set the appropriate labels on the pull request.
- [ ] I have added/updated the release note draft (if necessary).
- [ ] I have updated the documentation to reflect my changes (if necessary).
- [ ] All function and files are well documented. 
- [ ] All function and classes have type hints.
- [ ] There is a licenses in all file.
- [ ] The function and variable names are informative. 
- [ ] I have checked for code duplications.
- [ ] I have added new unittest (if necessary).

2024-06-20 18:06 UTC, ofirgo requested changes

2024-06-20 18:06 UTC, ofirgo commented on model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/functional_batch_norm.py
> +        if KERNEL in node.tensor_input_allocs:
is node a BN node? if so, why would it have kernel and bias?

2024-06-20 18:06 UTC, ofirgo commented on model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/functional_batch_norm.py
> +            weights_dict[GAMMA] = node.weights[3]
same question regarding the arbitrary constant "3"
(also, consider making these constant variables)

2024-06-20 18:06 UTC, ofirgo commented on model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/functional_batch_norm.py
>          convert functional batch_norm positional weights to BatchNorm2d weights
I dont understand why would the BN weights be positional and not regular parameters of the layer (maybe talk about this offline)

2024-06-20 18:06 UTC, ofirgo commented on model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/functional_layer_norm.py
>          Parse layer_norm(input, normalized_shape, weight=None, bias=None)
need to elaborate more (this doesn't explain what the function is doing)

2024-06-20 18:06 UTC, ofirgo commented on tests/pytorch_tests/model_tests/feature_models/bn_folding_test.py
> +        # TODO: remove this and set atol=1e-5 for all tests after fixing the issue with ConvTranspose2d.
attach a link to the issue on github in the comment

2024-06-23 07:37 UTC, elad-c commented on model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/const_holder_conv.py
> +        weight_index = func_node.tensor_input_allocs.index(KERNEL) if KERNEL in func_node.tensor_input_allocs else 1
default in the framework if weight and bias are in the args.

2024-06-23 07:41 UTC, elad-c commented on model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/const_holder_conv.py
> +        framework_attr = func_node.op_call_kwargs
Converting functional conv to conv module, so moving the kwargs to framework_attr, as the convention in the model reader.

2024-06-23 12:55 UTC, ofirgo commented on model_compression_toolkit/core/pytorch/reader/graph_builders.py
> +    Returns:
Return

2024-06-23 12:55 UTC, ofirgo commented on model_compression_toolkit/core/pytorch/reader/graph_builders.py
> +def is_instance_first_arg(n: Node, expected_type: Any) -> bool:
expected_type: Type?

2024-06-23 12:59 UTC, ofirgo approved these changes

2024-06-23 13:51 UTC, merged