fix find duplicates in qconfig
sony/model_optimization pull request #1155
Opened 2024-08-07 13:26 UTC by eladc-git

## Pull Request Description:

## Checklist before requesting a review:
- [ ] I set the appropriate labels on the pull request.
- [ ] I have added/updated the release note draft (if necessary).
- [ ] I have updated the documentation to reflect my changes (if necessary).
- [ ] All function and files are well documented. 
- [ ] All function and classes have type hints.
- [ ] There is a licenses in all file.
- [ ] The function and variable names are informative. 
- [ ] I have checked for code duplications.
- [ ] I have added new unittest (if necessary).

2024-08-08 06:11 UTC, elad-c requested changes

2024-08-08 06:11 UTC, elad-c commented on model_compression_toolkit/core/common/graph/base_node.py
> +            if len(matching_qcos) > 1 and matching_qcos[0] != tpc.tp_model.default_qco:
1. Must the deafult be at index 0?
2. Add a test to simulate it.

2024-08-08 07:57 UTC, ofirgo commented on model_compression_toolkit/core/common/graph/base_node.py
> +            if len(matching_qcos) > 1 and matching_qcos[0] != tpc.tp_model.default_qco:
I don't think that this solves the issue correctly.
I suspect that the case generating this issue is when there is a pytorch function that has two aliases, and that one of them appears in a TPC operation set and the other is not, thus returning the default qco.

Please try to reproduce the issue, identify the pytorch layer that has duplicate configs and let's think of a more robust solution.

2024-12-01 08:46 UTC, closed without merging

2024-12-01 08:46 UTC, elad-c commented
Issue will be fixed in another PR.