Fix issue with reuse layers in torch
sony/model_optimization pull request #1217
Opened 2024-09-15 15:10 UTC by reuvenperetz

## Pull Request Description:
Fix the issue of ignoring shared params in reused layers in torch models.

## Checklist before requesting a review:
- [ ] I set the appropriate labels on the pull request.
- [ ] I have added/updated the release note draft (if necessary).
- [ ] I have updated the documentation to reflect my changes (if necessary).
- [ ] All function and files are well documented. 
- [ ] All function and classes have type hints.
- [ ] There is a licenses in all file.
- [ ] The function and variable names are informative. 
- [ ] I have checked for code duplications.
- [ ] I have added new unittest (if necessary).

2024-09-24 19:55 UTC, irenaby commented on model_compression_toolkit/core/pytorch/reader/graph_builders.py
> +        if node_group_key in seen_targets and len(weights) > 0:
Is there any reason not to mark all reused nodes, for consistency?

2024-09-24 19:55 UTC, irenaby commented on model_compression_toolkit/core/pytorch/reader/graph_builders.py
> +    Combine target and weights to create a unique reuse group identifier.
Maybe mention that weights are needed for functional ops

2024-09-24 19:55 UTC, irenaby commented on tests/pytorch_tests/model_tests/feature_models/reuse_layer_net_test.py
> +        x = F.conv2d(x, self.conv2_weight, self.conv2_bias, stride=1, groups=1)
I would add a case where weight is identical but not bias and vice versa to make sure both are taken into account

2024-09-24 19:55 UTC, irenaby commented on model_compression_toolkit/core/pytorch/reader/graph_builders.py
> +        if node_group_key in seen_targets and len(weights) > 0:
Is there any reason not to mark all reused layers for consistency?

2024-09-24 19:55 UTC, irenaby commented on model_compression_toolkit/core/pytorch/reader/graph_builders.py
> +    Combine target and weights to create a unique reuse group identifier.
Maybe mention that weights are needed for functional ops

2024-09-24 19:55 UTC, irenaby commented on tests/pytorch_tests/model_tests/feature_models/reuse_layer_net_test.py
> +        x = F.conv2d(x, self.conv2_weight, self.conv2_bias, stride=1, groups=1)
I would also check that identical weight but different bias and vice versa are not considered reused

2024-09-24 19:55 UTC, irenaby commented on tests/pytorch_tests/model_tests/feature_models/reuse_layer_net_test.py
>      def create_feature_network(self, input_shape):
Why not implement this method directly instead of making it call another method that should be implemented?

2024-09-24 19:55 UTC, irenaby commented on tests/pytorch_tests/model_tests/feature_models/reuse_layer_net_test.py
> +class BaseReuseLayerNet(nn.Module):
Do you really need this class? I think you are over engineering

2024-09-24 19:55 UTC, irenaby commented on tests/pytorch_tests/model_tests/feature_models/reuse_layer_net_test.py
> +    def compare(self, quantized_models, float_model, input_x=None, quantization_info=None):
Consider implementing explicit compare in the concrete tests. IMO in tests simplicity and clarity is more important than a perfect OOP.

2024-09-25 06:20 UTC, ofirgo commented on model_compression_toolkit/core/pytorch/reader/graph_builders.py
> +    named_parameters = {name: parameter for name, parameter in module.named_parameters()}
Can you explain why you removed numpy conversion? seems like something that might have effect on different modules, and is not directly related to reused layers

2024-09-25 06:20 UTC, ofirgo commented on tests/pytorch_tests/model_tests/feature_models/reuse_layer_net_test.py
> +        layer_calls = {}
I would also suggest changing `fx_node_2_graph_node` to defaultdict.
Let's start improving all our code according to the recent principles that we presented, not just our new code :)

2024-09-25 07:11 UTC, ofirgo requested changes

2024-09-25 08:17 UTC, ofirgo approved these changes

2024-09-25 11:19 UTC, merged