Pytorch Feature Tutorials Refactor
sony/model_optimization pull request #1225
Opened 2024-09-19 09:49 UTC by lior-dikstein

## Pull Request Description:
Refactored Pytorch feature notebooks for consistency. Standardized function usage across notebooks. Updated model examples to use pretrained models from torchvision with the ImageNet validation set as the representative dataset (except for the pruning notebook).

## Checklist before requesting a review:
- [ ] I set the appropriate labels on the pull request.
- [ ] I have added/updated the release note draft (if necessary).
- [ ] I have updated the documentation to reflect my changes (if necessary).
- [ ] All function and files are well documented. 
- [ ] All function and classes have type hints.
- [ ] There is a licenses in all file.
- [ ] The function and variable names are informative. 
- [ ] I have checked for code duplications.
- [ ] I have added new unittest (if necessary).

2024-09-23 10:50 UTC, ofirgo requested changes

2024-09-23 10:50 UTC, ofirgo commented on tutorials/notebooks/mct_features_notebooks/pytorch/example_pytorch_post_training_quantization.ipynb
> +    "3. Hardware-Friendly Post-Training Quantization using MCT.\n",
I think we can remove the "Hardware-friendly" term from this tutorial, the weights thresholds are no longer POT (in the default TPC) and this is not important in the scope of the tutorial and its purpose.

2024-09-23 10:50 UTC, ofirgo commented on tutorials/notebooks/mct_features_notebooks/pytorch/example_pytorch_post_training_quantization.ipynb
> +    "print(quantized_model)"
remove

2024-09-25 13:28 UTC, lior-dikstein commented on tutorials/notebooks/mct_features_notebooks/pytorch/example_pytorch_data_generation.ipynb
> +    "batches_inds = np.random.choice(len(generated_images),\n",
It can, but its best practice to do it this way to get the best results

2024-09-26 07:44 UTC, lior-dikstein commented on tutorials/notebooks/mct_features_notebooks/pytorch/example_pytorch_mixed_precision_ptq.ipynb
> +    "We will set a random seed to ensure reproducibility of results."
I erased it.

2024-09-26 09:43 UTC, ofirgo approved these changes

2024-09-26 10:14 UTC, merged