Combined nbits configs for weights and activations
sony/model_optimization pull request #123
Opened 2022-03-27 09:14 UTC by ofirgo

* Coupling weights and activations nbits to one combined quantization configuration, as a preliminary step for activation mixed precision.

* Using a list of configuration candidates for each layer such that each candidate is constructed from both weights and activation configuration (currently, activation config is equal for all candidates).

2022-03-28 16:01 UTC, reuvenperetz requested changes

2022-03-29 06:01 UTC, ofirgo commented on model_compression_toolkit/common/quantization/quantization_params_generation/qparams_computation.py
Not sure I understand. It can't be indented back since there is no if statement there

2022-03-29 06:05 UTC, ofirgo commented on model_compression_toolkit/keras/quantizer/mixed_precision/selective_quantizer.py
> +            assert qc.weights_quantization_cfg.weights_quantization_fn == quantizer_fn
You mean, do not require that the quantizers of all candidates would be equal? (just want to make sure)

2022-03-29 06:10 UTC, ofirgo commented on model_compression_toolkit/pytorch/quantization_facade.py
>              return pytorch_post_training_quantization(in_model,
What do you mean by "unmatch"? it would still be one of the candidates (the one with the maximal weights precision)

2022-03-29 06:13 UTC, ofirgo commented on model_compression_toolkit/common/quantization/quantization_params_generation/qparams_activations_computation.py
Only in the "else" condition or also in "get_min_max_values()"?

2022-03-29 06:15 UTC, ofirgo commented on model_compression_toolkit/keras/quantization_facade.py
>              return keras_post_training_quantization(in_model,
What do you mean by "unmatch"? it would still be one of the candidates (the one with the maximal weights precision)

2022-03-29 06:16 UTC, ofirgo commented on model_compression_toolkit/pytorch/mixed_precision/mixed_precision_wrapper.py
> +            assert qc.weights_quantization_cfg.weights_quantization_fn == self.quantizer_fn
same question as in the previous comment

2022-03-29 06:29 UTC, ofirgo commented on model_compression_toolkit/common/network_editors/actions.py
> +            for candidate_config in node.candidates_quantization_cfg:
Just to make sure I understand correctly, so if node.final_weights_quantization_cfg is None we don't want to do anything in this action? (verify my change before resolving the issue)

2022-03-29 09:17 UTC, merged