Mha decomposition update
sony/model_optimization pull request #164
Opened 2022-04-25 13:22 UTC by elad-c

MHA node decomposition update: implement MHA iterations with layers reuse instead of folding the iterations to batch

2022-04-26 15:38 UTC, reuvenperetz requested changes

2022-04-26 15:38 UTC, reuvenperetz commented on model_compression_toolkit/keras/graph_substitutions/substitutions/multi_head_attention_decomposition.py
> +        """
Please use Numpy documentation convention

2022-04-26 15:38 UTC, reuvenperetz commented on model_compression_toolkit/keras/graph_substitutions/substitutions/multi_head_attention_decomposition.py
> +                    }
Please use REUSED_IDENTIFIER from node_builder

2022-04-26 15:38 UTC, reuvenperetz commented on model_compression_toolkit/keras/graph_substitutions/substitutions/multi_head_attention_decomposition.py
> +
Same (REUSED_IDENTIFIER...)

2022-04-26 15:38 UTC, reuvenperetz commented on model_compression_toolkit/keras/graph_substitutions/substitutions/multi_head_attention_decomposition.py
> +        :param iter_index: iteration index
Please complete missing arguments

2022-04-27 09:36 UTC, elad-c commented on model_compression_toolkit/keras/graph_substitutions/substitutions/multi_head_attention_decomposition.py
> +        """
Google convention :)

2022-04-27 11:00 UTC, reuvenperetz approved these changes

2022-04-27 11:01 UTC, merged