Add MultiHeadAttention Layer decomposition for PyTorch
sony/model_optimization pull request #244
Opened 2022-05-23 11:14 UTC by lapid92

2022-05-23 14:44 UTC, elad-c requested changes

2022-05-23 14:44 UTC, elad-c commented on model_compression_toolkit/pytorch/graph_substitutions/substitutions/multi_head_attention_decomposition.py
> +        # (B, q_seq, q_dim*n_h) --> (B, q_dim*n_h, q_seq) --> (B, q_dim*n_h, q_seq)
Add comment to explain the comment

2022-05-23 14:44 UTC, elad-c commented on model_compression_toolkit/pytorch/graph_substitutions/substitutions/multi_head_attention_decomposition.py
> +        factor = (params.qdim ** -0.5)
Add comment  to explain the weight calcualtion process

2022-05-23 14:44 UTC, elad-c commented on model_compression_toolkit/pytorch/graph_substitutions/substitutions/multi_head_attention_decomposition.py
> +        # (B, q_seq, q_dim*n_h) --> (B, q_dim*n_h, q_seq)
Add comment explaining why the transepose is needed

2022-05-23 14:44 UTC, elad-c commented on model_compression_toolkit/pytorch/graph_substitutions/substitutions/multi_head_attention_decomposition.py
> +    def _arrange_before_slice(graph, mha_node, q_node, k_node, v_node, params):
change to "split"

2022-05-23 14:44 UTC, elad-c commented on model_compression_toolkit/pytorch/graph_substitutions/substitutions/multi_head_attention_decomposition.py
> +        # # (B, n_h, q_seq, q_dim) --> (B, 1, q_seq, q_dim) --> (B, q_seq, q_dim)
delete unnecessary comment

2022-05-23 14:44 UTC, elad-c commented on model_compression_toolkit/pytorch/graph_substitutions/substitutions/multi_head_attention_decomposition.py
> +        # [(B, 1, q_seq, q_dim)]  * n_h --> (B, 1, n_h, q_seq, q_dim) --> (B, n_h, q_seq, q_dim)
change to concat on 2nd axis instead of stack&reshape

2022-05-23 14:44 UTC, elad-c commented on model_compression_toolkit/pytorch/graph_substitutions/substitutions/multi_head_attention_decomposition.py
> +        if DROPOUT in mha_node.framework_attr:
no need for this limitation: we only run inference mode, so dropout is an identity

2022-05-23 14:44 UTC, elad-c commented on model_compression_toolkit/pytorch/graph_substitutions/substitutions/multi_head_attention_decomposition.py
> +        if ADD_ZERO_ATTN in mha_node.framework_attr.keys():
Check if we need to support this

2022-05-23 14:44 UTC, elad-c commented on model_compression_toolkit/pytorch/graph_substitutions/substitutions/multi_head_attention_decomposition.py
> +            if mha_node.framework_attr[ADD_BIAS_KV] is not False:
Check if we need to support this

2022-05-23 19:15 UTC, reuvenperetz requested changes

2022-05-23 19:15 UTC, reuvenperetz commented on model_compression_toolkit/pytorch/graph_substitutions/substitutions/multi_head_attention_decomposition.py
> +        return [k for k in mha_node.weights.keys() if w_str in k][0]
Why not use mha node's get_weights_by_keys method?

2022-05-23 19:15 UTC, reuvenperetz commented on model_compression_toolkit/pytorch/graph_substitutions/substitutions/multi_head_attention_decomposition.py
> +
Please add comments and type hints.

2022-05-23 19:15 UTC, reuvenperetz commented on model_compression_toolkit/pytorch/graph_substitutions/substitutions/multi_head_attention_decomposition.py
> +
Please remove the "returns" line

2022-05-23 19:15 UTC, reuvenperetz commented on model_compression_toolkit/pytorch/graph_substitutions/substitutions/multi_head_attention_decomposition.py
> +        connect subgraph to input graph
Please add type hints

2022-05-23 19:15 UTC, reuvenperetz commented on model_compression_toolkit/pytorch/graph_substitutions/substitutions/multi_head_attention_decomposition.py
> +
Please let's use a different error message

2022-05-25 13:26 UTC, elad-c approved these changes

2022-05-25 15:34 UTC, merged