Add new fusions to default and fix bug in fusion algorithm
sony/model_optimization pull request #249
Opened 2022-05-25 13:19 UTC by eladc-git

2022-05-25 15:32 UTC, reuvenperetz requested changes

2022-05-25 15:36 UTC, eladc-git commented on tests/keras_tests/feature_networks_tests/feature_networks/nested_networks/nested_model_multiple_inputs_test.py
>          self.unit_test.assertTrue(len(quantized_model.layers) == (num_layers+num_fq_layers))
Because of the bug fix in the algorithm. It makes fusion when it not supposed to do.

2022-05-25 15:36 UTC, eladc-git commented on model_compression_toolkit/common/fusion/layer_fusing.py
>      """
OK

2022-05-25 15:37 UTC, eladc-git commented on model_compression_toolkit/tpc_models/keras_tp_models/keras_default.py
> +
no ops in keras only in pytorch

2022-05-26 06:55 UTC, reuvenperetz commented on model_compression_toolkit/tpc_models/keras_tp_models/keras_default.py
> +
So I think we can remove the hard swish line

2022-05-26 07:19 UTC, eladc-git commented on model_compression_toolkit/tpc_models/keras_tp_models/keras_default.py
> +
I wish. but TP (for pytorch) has it so TPC is crying if it will be missing (for keras).

2022-05-26 11:34 UTC, eladc-git commented on model_compression_toolkit/tpc_models/keras_tp_models/keras_default.py
> +
Done

2022-05-26 11:59 UTC, merged