Add Gumbel rounding
sony/model_optimization pull request #289
Opened 2022-07-06 08:22 UTC by haihabi

Refactor quantizer in GPTQ
Adding Gumbel Rounding quantizers

2022-07-06 13:05 UTC, reuvenperetz commented on model_compression_toolkit/gptq/common/gptq_config.py
> +    def is_gumbel(self) -> bool:
Missing comment

2022-07-06 13:13 UTC, reuvenperetz commented on model_compression_toolkit/gptq/keras/gptq_training.py
> +        """
In general, it seems that this function is redundant. The logic of computing and applying the gradients are in train. Maybe we should use a function for both of them as the difference is the number of training iterations.

2022-07-06 13:31 UTC, elad-c requested changes

2022-07-06 13:31 UTC, elad-c commented on model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/uniform_gumbel.py
> +        auxvar_tensor:
auxvar_tensor comment

2022-07-06 13:31 UTC, elad-c commented on model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/uniform_gumbel.py
> +    def calc_quant_config(self, layer):
get_quant_config seems better
return type hint

2022-07-06 13:31 UTC, elad-c commented on model_compression_toolkit/gptq/keras/quantizer/kernel_functions.py
> +    This function take an threshold tensor and re-aline it to the weight tensor channel axis.
takes a

2022-07-06 13:45 UTC, haihabi commented on model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/gumbel_softmax.py
> +    delta = tf.stop_gradient(select_gumbel(in_prob) - in_prob)
Explain?

2022-07-06 13:54 UTC, haihabi commented on model_compression_toolkit/gptq/keras/quantizer/configs/weight_quantizer_gptq_config.py
> +#
Why this is an old file

2022-07-06 13:58 UTC, reuvenperetz requested changes

2022-07-06 13:58 UTC, reuvenperetz commented on model_compression_toolkit/gptq/keras/quantizer/configs/weight_quantizer_gptq_config.py
> +
Maybe we should use it in the gptq constants

2022-07-06 13:58 UTC, reuvenperetz commented on model_compression_toolkit/gptq/keras/quantizer/configs/weight_quantizer_gptq_config.py
> +        """
Type hints (to all methods in this file)

2022-07-06 14:02 UTC, haihabi commented on model_compression_toolkit/gptq/keras/gptq_training.py
> +                gumbel_prob = get_gumbel_probability(self.fxp_model)
No

2022-07-06 14:04 UTC, haihabi commented on model_compression_toolkit/gptq/keras/gptq_training.py
> +            w2train = self.flattened_trainable_weights
Nice catch

2022-07-06 18:53 UTC, reuvenperetz requested changes

2022-07-06 18:53 UTC, reuvenperetz commented on model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/base_gumbel_rounding.py
> +def _init_aux_var(w_shape, m):
Comments and type hints.

2022-07-06 18:53 UTC, reuvenperetz commented on model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/base_gumbel_rounding.py
> +    p = 0.01
Please use a constant.

2022-07-06 18:53 UTC, reuvenperetz commented on model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/base_gumbel_rounding.py
> +    m_hat = m // 2
Comments and type hints.

2022-07-07 06:42 UTC, reuvenperetz approved these changes

2022-07-07 08:07 UTC, merged