update QAT and add export API
sony/model_optimization pull request #308
Opened 2022-07-27 10:08 UTC by elad-c

1. Add weight quantization in case there are weights not to be fine-tuned
2. Add export method to remove QuantizeWrappers from the QAT model after fine-tuning
3. Update docsrc with new API

2022-07-27 14:56 UTC, haihabi commented on model_compression_toolkit/qat/keras/quantization_facade.py
> +    def keras_quantization_aware_training_export(in_model: Model):
Rename the function from export to finalizing or something alone the line( this is true in several locations).

2022-07-28 07:34 UTC, reuvenperetz requested changes

2022-07-28 07:34 UTC, reuvenperetz commented on model_compression_toolkit/qat/keras/model_builder.py
> +    is_class_quantized = node.layer_class in [tf.keras.layers.Conv2D,
Use node.type

2022-07-28 07:34 UTC, reuvenperetz commented on model_compression_toolkit/qat/keras/model_builder.py
> +        node (Model): Keras model to quantize.
Fix comment

2022-07-28 07:34 UTC, reuvenperetz commented on model_compression_toolkit/qat/keras/model_builder.py
> +    is_weight_quantization = node.final_weights_quantization_cfg.enable_weights_quantization
Please use node's method is_weights_quantization_enabled instead

2022-07-31 09:39 UTC, reuvenperetz requested changes

2022-07-31 09:39 UTC, reuvenperetz commented on model_compression_toolkit/core/common/defaultdict.py
> +        Get keys od known_dict
Typo

2022-07-31 10:24 UTC, merged