Add keras QAT tutorial
sony/model_optimization pull request #320
Opened 2022-08-03 15:06 UTC by elad-c

Tutorial for quantizing a simple keras model with the QAT API

2022-08-03 19:48 UTC, haihabi commented on tutorials/example_keras_qat.py
> +from model_compression_toolkit.qat.keras.quantization_facade import DEFAULT_KERAS_TPC as default_tpc
Please use the official API and don't use imports from inside MCT

2022-08-03 19:49 UTC, haihabi commented on tutorials/example_keras_qat.py
> +num_classes = 10
Create several functions
1. Network creation
2. Dataset creation

2022-08-03 19:49 UTC, haihabi commented on tutorials/example_keras_qat.py
> +batch_size = 128
Put all the parameters in a single place

2022-08-03 19:50 UTC, haihabi commented on tutorials/example_keras_qat.py
> +_input = layers.Input(shape=input_shape)
add if __main__:

2022-08-03 19:52 UTC, haihabi commented on tutorials/example_keras_qat.py
> +default_tpc.tp_model.default_qco.base_config.weights_n_bits = 2
Please remove those lines and let's think of a different option.
Maybe we should build an example TPC in the tutorials folder and use it.

2022-08-04 11:58 UTC, reuvenperetz requested changes

2022-08-04 11:58 UTC, reuvenperetz commented on tutorials/example_keras_qat.ipynb
> +     "text": [
Remove notebook outputs

2022-08-04 11:58 UTC, reuvenperetz commented on tutorials/example_keras_qat.ipynb
> +      "File \u001b[0;32m/data/projects/swat/envs/eladc/jupyterlab/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py:26\u001b[0m, in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[
Same...

2022-08-09 09:02 UTC, reuvenperetz commented on tutorials/example_keras_qat.py
> +    tp = mct.target_platform
Please fix comment: We're generating a Keras TargetPlatformCapabilities with 3 bits...

2022-08-09 10:48 UTC, haihabi commented on tutorials/example_keras_qat.py
> +def get_tpc():
Please put comment to all functions

2022-08-09 10:50 UTC, haihabi commented on tutorials/example_keras_qat.py
> +                                                                 target_platform_capabilities=get_tpc())
Please add a comment on why we use here a different TPC and how to obtain HW-specific TPC.

2022-08-09 10:51 UTC, haihabi commented on tutorials/example_keras_qat.py
> +import tensorflow as tf
Add Licence

2022-08-09 10:52 UTC, haihabi commented on tutorials/example_keras_qat.ipynb
> +{
Ask amir.t how to put a Licence in notebooks.

2022-08-09 15:44 UTC, reuvenperetz approved these changes

2022-08-10 07:13 UTC, merged