Gumbel Rounding API and Testing Update
sony/model_optimization pull request #321
Opened 2022-08-03 19:46 UTC by haihabi

1. Add to the GPTQ configuration the Gumbel rounding config
2. Add several future testing for GPTQ

2022-08-04 11:20 UTC, reuvenperetz requested changes

2022-08-04 11:20 UTC, reuvenperetz commented on model_compression_toolkit/gptq/common/gptq_config.py
> +            optimizer_bias (Any): Optimizer o override the rest optimizerfor bias.
Optimizer to override...

2022-08-04 11:20 UTC, reuvenperetz commented on model_compression_toolkit/gptq/keras/quantization_facade.py
> +                              optimizer: OptimizerV2 = tf.keras.optimizers.Adam(learning_rate=0.2),
Please use constants.
Also, please update the comment about the default optimizer.

2022-08-04 11:20 UTC, reuvenperetz commented on model_compression_toolkit/gptq/common/gptq_config.py
> +            quantizer_config (Any): A class the contins the quantizer specific config.
Maybe we should rename it to gumbel_config?

2022-08-04 11:20 UTC, reuvenperetz commented on model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/symmetric_gumbel.py
> +                 threshold_values: np.ndarray, gumbel_config: GumbelConfig,
Use a new line, please

2022-08-04 12:00 UTC, reuvenperetz commented on model_compression_toolkit/gptq/common/gptq_config.py
> +    """
Please expose this class in API and let's add it to docsrc

2022-08-07 07:14 UTC, haihabi commented on model_compression_toolkit/gptq/common/gptq_config.py
> +            quantizer_config (Any): A class the contins the quantizer specific config.
No, in the future we may have a config for other quantizers.

2022-08-07 07:17 UTC, reuvenperetz approved these changes

2022-08-07 07:17 UTC, reuvenperetz commented on model_compression_toolkit/gptq/common/gptq_config.py
> +            quantizer_config (Any): A class the contins the quantizer specific config.
Please fix the type of quantizer_config

2022-08-07 07:21 UTC, merged