Move functions to common
sony/model_optimization pull request #339
Opened 2022-08-16 10:53 UTC by eladc-git

2022-08-16 14:43 UTC, reuvenperetz requested changes

2022-08-16 14:43 UTC, reuvenperetz commented on model_compression_toolkit/gptq/common/gptq_training.py
> +                                 temperature_weights):
Please add comments and type hints

2022-08-17 05:27 UTC, eladc-git commented on model_compression_toolkit/gptq/common/gptq_training.py
> +                                 temperature_weights):
done

2022-08-17 07:06 UTC, reuvenperetz approved these changes

2022-08-17 07:52 UTC, haihabi commented
I am not sure about this PR since there is a significant difference between Keras and PyTorch optimizers.
Let's talk about it. Maybe we need to change Keras API.

2022-08-17 09:30 UTC, eladc-git commented
> I am not sure about this PR since there is a significant difference between Keras and PyTorch optimizers. Let's talk about it. Maybe we need to change Keras API.

This code is only optimizer object and weights holder so it is not supposed to be framework related.

2022-08-17 14:19 UTC, merged