Statistics correction
sony/model_optimization pull request #372
Opened 2022-09-12 17:42 UTC by lapid92

Add second moment correction in addition to bias correction
  Add second moment correction tests

2022-09-14 06:38 UTC, elad-c requested changes

2022-09-14 06:38 UTC, elad-c commented on model_compression_toolkit/core/common/statistics_correction/apply_second_moment_correction_to_graph.py
> +    analyzer_graph(fw_impl.attach_sc_to_node,
This code is repeated, consider putting it in a function

2022-09-14 06:38 UTC, elad-c commented on model_compression_toolkit/core/common/statistics_correction/apply_second_moment_correction_to_graph.py
> +def _assign_act_threshold(graph: Graph,
rename to collect and assign...

2022-09-14 06:38 UTC, elad-c commented on model_compression_toolkit/core/keras/graph_substitutions/substitutions/batchnorm_reconstructing.py
> +        assert len(graph.nodes) - num_nodes_before_substitution == 1
Make this check in tests

2022-09-14 06:38 UTC, elad-c commented on model_compression_toolkit/core/keras/graph_substitutions/substitutions/batchnorm_refusing.py
> +# Copyright 2021 Sony Semiconductor Israel, Inc. All rights reserved.
2022

2022-09-14 06:38 UTC, elad-c commented on model_compression_toolkit/core/keras/graph_substitutions/substitutions/batchnorm_refusing.py
> +    conv_node = NodeOperationMatcher(DepthwiseConv2D) | \
Same question about Dense

2022-09-14 06:38 UTC, elad-c commented on model_compression_toolkit/core/keras/graph_substitutions/substitutions/batchnorm_refusing.py
> +def update_kernel_for_bn_refusing_fn(conv_node: BaseNode,
Consider using the function from batch_norm_folding

2022-09-14 06:38 UTC, elad-c commented on model_compression_toolkit/core/keras/keras_implementation.py
> +        # needs to check if gamma&beta are the same?
Answer the question and remove the TODO. Probably not, check that in tests

2022-09-14 06:38 UTC, elad-c commented on model_compression_toolkit/core/keras/keras_implementation.py
> +        for layer in model.layers:
This a potential bug, needto set this for reconstrusted BN only

2022-09-14 06:38 UTC, elad-c commented on model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/batchnorm_reconstructing.py
> +    def substitute(self,
Consider moving this function to a parent class in common.

2022-09-15 14:46 UTC, reuvenperetz requested changes

2022-09-15 14:46 UTC, reuvenperetz commented on model_compression_toolkit/core/keras/graph_substitutions/substitutions/batchnorm_refusing.py
> +        kernel = kernel * weights_scale.reshape(1, 1, 1, -1)
Why not take the channel axis from framework info?

2022-09-15 14:46 UTC, reuvenperetz commented on model_compression_toolkit/core/keras/graph_substitutions/substitutions/batchnorm_refusing.py
> +                                     weights_scale):
Missing type hints

2022-09-15 14:46 UTC, reuvenperetz commented on model_compression_toolkit/core/keras/graph_substitutions/substitutions/batchnorm_refusing.py
> +    """
Missing type hints

2022-09-15 14:46 UTC, reuvenperetz commented on model_compression_toolkit/core/keras/graph_substitutions/substitutions/batchnorm_refusing.py
> +        The modified convolution node's weight/kernel/
Please fix typo (at the end of the sentence)

2022-09-15 14:46 UTC, reuvenperetz commented on model_compression_toolkit/core/pytorch/constants.py
>  MOVING_MEAN = 'running_mean'
Why did you remove these two constants? (KERNEL_SIZE, IN_CHANNELS)

2022-09-15 14:46 UTC, reuvenperetz commented on model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/batchnorm_refusing.py
> +        The modified convolution node's weight/kernel/
Please fix typo, and add missing type hints

2022-09-15 14:46 UTC, reuvenperetz commented on model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/batchnorm_refusing.py
> +    """
Missing type hints

2022-09-15 14:46 UTC, reuvenperetz commented on model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/batchnorm_refusing.py
> +                  NodeOperationMatcher(ConvTranspose2d)
As @elad-c mentioned - shouldn't Linear be here as well?

2022-09-15 14:46 UTC, reuvenperetz commented on model_compression_toolkit/core/pytorch/pytorch_implementation.py
> +        """
Maybe it's worth considering writing this method in a dedicated file and importing it (Relevant for Keras as well)?

2022-09-15 14:46 UTC, reuvenperetz commented on model_compression_toolkit/core/pytorch/pytorch_implementation.py
> +    def apply_second_moment_correction(self, quantized_model, core_config, representative_data_gen, graph):
Missing type hints

2022-09-15 14:46 UTC, reuvenperetz commented on model_compression_toolkit/core/pytorch/pytorch_implementation.py
> +        # Move every BN to eval mode and update the corresponding BN node params in the graph
Indeed - this should be verified as a test

2022-09-15 14:46 UTC, reuvenperetz commented on model_compression_toolkit/core/pytorch/pytorch_implementation.py
> +                # check if to set w by key?
Please remove the TODO

2022-09-15 14:46 UTC, reuvenperetz commented on model_compression_toolkit/core/pytorch/pytorch_implementation.py
> +        """
This method is duplicated for both Keras and PyTorch implementations. Consider moving it to common

2022-09-15 14:46 UTC, reuvenperetz commented on model_compression_toolkit/core/common/substitutions/batchnorm_refusing.py
> +        # if gamma or beta is None raise Exception
Please remove this TODO

2022-09-15 14:46 UTC, reuvenperetz commented on model_compression_toolkit/core/common/substitutions/batchnorm_refusing.py
> +            framework_attr[self.layer_name_str] = conv_node.name + '_refused'
Please use it as a constant (not in constants file, as this is relevant only to this scope, if I'm not missing anything)

2022-09-15 14:46 UTC, reuvenperetz commented on model_compression_toolkit/core/common/substitutions/batchnorm_refusing.py
> +        conv_bn_name = conv_node.name + '_refused'
Same as above-mentioned.

2022-09-15 14:46 UTC, reuvenperetz commented on model_compression_toolkit/core/common/substitutions/batchnorm_refusing.py
> +    def _calc_weights_quantization_params(self,
Missing type hints

2022-09-21 10:35 UTC, lapid92 commented on model_compression_toolkit/core/runner.py
> +    transformed_graph = substitute(transformed_graph, fw_impl.get_substitutions_statistics_correction(quant_config))
The bias correction (compute_bias_correction) should also be called from the ptq_runner?

2022-09-22 09:04 UTC, elad-c approved these changes

2022-09-28 08:29 UTC, reuvenperetz approved these changes

2022-09-28 14:38 UTC, merged