Add target platform export package with TF FQ export
sony/model_optimization pull request #376
Opened 2022-09-19 14:01 UTC by reuvenperetz

Added a new package named target_platform_export.
Base Exporter class, BaseKerasExporter, and FakelyQuantKerasExporter were added.
Each exporter needs to implement export and save_model methods.
Tests were added as well.

2022-09-20 12:42 UTC, haihabi commented on model_compression_toolkit/exporter/target_platform_export/keras/exporters/int8_keras_exporter.py
> +        pass
Change to raise not implamented

2022-09-21 07:29 UTC, ofirgo commented on model_compression_toolkit/exporter/fully_quantized/keras/builder/quantize_config_to_node.py
> +SUPPORTED_QUANTIZATION_CONFIG = [WeightsQuantizeConfig,
Not sure if this is the best location for this list, especially if it is not used in the context of this file.
Consider moving it to [fakely_quant_keras_exporter.py](https://github.com/sony/model_optimization/pull/376/files#diff-9fc31c2e54b68e28a9a9a580aaa65fb795d8a7b80db7538451c1095c2585a5a2) if it is only used there.

2022-09-21 07:31 UTC, ofirgo commented on model_compression_toolkit/exporter/target_platform_export/fw_agonstic/exporter.py
> +    Base class to define API for an Exporter class that exports and save models.
Really picky.. "exports and save**s**.."

2022-09-21 07:34 UTC, ofirgo commented on model_compression_toolkit/exporter/target_platform_export/keras/export_keras_fully_quantized_model.py
> +                                       save_model_path: str = None):
Please add return type hint

2022-09-21 07:35 UTC, ofirgo commented on model_compression_toolkit/exporter/target_platform_export/keras/export_keras_fully_quantized_model.py
> +
Please remove blank lines

2022-09-21 07:36 UTC, ofirgo commented on model_compression_toolkit/exporter/target_platform_export/keras/exporters/base_keras_exporter.py
> +
Please remove blank lines

2022-09-21 07:40 UTC, ofirgo commented on model_compression_toolkit/exporter/target_platform_export/keras/exporters/fakely_quant_keras_exporter.py
> +    Exporter for fakely-quant Keras models.
Consider extend the description for the exporter classes (also in Int8 exporter even though it is not implemented yet).
The terminology is not necessarily clear, maybe add something like "In a fakely-quant model all quantized tensors values are still saved in float32, but are quantized to a set of finite values according to the chosen quantization grid..."
(not necessarily this phrasing but the general idea...)

2022-09-21 07:41 UTC, ofirgo commented on model_compression_toolkit/exporter/target_platform_export/keras/exporters/fakely_quant_keras_exporter.py
> +        def _unwrap_quantize_wrapper(layer:Layer):
Please add return type hint

2022-09-21 07:44 UTC, ofirgo commented on model_compression_toolkit/exporter/target_platform_export/keras/exporters/fakely_quant_keras_exporter.py
> +                # For now, we assume only weights are quantized for models to export. Activation support is in progress.
I would print that to the logs (info) at the initiation of the exporter class (maybe even in the base exporter class). I think this is an important note.
Also - is there a way to assert this? that if we get a model with quantize activations (look for fake quant layers) maybe log this as a warning that says that the given model's activations are quantized but the exported model would only have quantized weights?

2022-09-21 07:49 UTC, ofirgo commented on model_compression_toolkit/exporter/target_platform_export/keras/exporters/fakely_quant_keras_exporter.py
> +                    new_layer = layer.layer.__class__.from_config(layer.layer.get_config())
this call looks a bit odd.. are you sure that is the correct way ti call "from_config" (using the __class__ attribute)?

2022-09-21 07:51 UTC, ofirgo commented on model_compression_toolkit/exporter/target_platform_export/keras/exporters/fakely_quant_keras_exporter.py
> +                                    val = layer.quantize_config.get_weights_and_quantizers(layer.layer)[0][1].weight
Accessing [0] and then [1] - are we sure that the returned lists are at the right length? maybe assert this?

2022-09-21 07:53 UTC, ofirgo commented on tests/keras_tests/function_tests/test_export_keras_fully_quantized_model.py
> +SAVED_MODEL_PATH = '/tmp/exported_tf.h5'
Are the models automatically removed after the test is finished?

2022-09-21 07:55 UTC, ofirgo commented on tests/keras_tests/function_tests/test_export_keras_fully_quantized_model.py
> +        self.representative_data_gen = lambda: [np.random.randn(1, 224, 224, 3)]
Just verifying - if this test supposed to run in the test suite, wouldn't it take very long because of the large model?

2022-09-21 07:57 UTC, ofirgo requested changes
Design seems good, just few cosmetic comments and some minor questions for discussion

2022-12-04 10:34 UTC, closed without merging