Inferable quantizers
sony/model_optimization pull request #505
Opened 2023-01-02 18:38 UTC by reuvenperetz

2023-01-03 06:51 UTC, haihabi commented on model_compression_toolkit/qunatizers_infrastructure/keras/inferable_quantizers/inferable_quantizer_factory.py
> +QUANTIZATION_METHOD_2_QUANTIZER = {QuantizationMethod.POWER_OF_TWO: POTInferableQuantizer,
Why do we need a factory?

2023-01-03 06:51 UTC, haihabi commented on model_compression_toolkit/qunatizers_infrastructure/keras/inferable_quantizers/pot_inferable_quantizer.py
> +class POTInferableQuantizer(SymmetricInferableQuantizer):
We not have a sperate quantizer for activation and weights ?

2023-01-05 12:53 UTC, eladc-git requested changes

2023-01-05 12:53 UTC, eladc-git commented on model_compression_toolkit/exporter/model_wrapper/keras/builder/fully_quantized_model_builder.py
> +                 layer: Layer):
output type

2023-01-05 12:53 UTC, eladc-git commented on model_compression_toolkit/exporter/model_wrapper/keras/builder/node_to_quantizer.py
> +                    'threshold': node_qc.activation_quantization_params.get(THRESHOLD),
What about PO2 bool flag? We don't want the convertor to do some calculations on threshold to check it? same for weights quantizers.

2023-01-05 12:53 UTC, eladc-git commented on model_compression_toolkit/qunatizers_infrastructure/keras/inferable_quantizers/activation_inferable_quantizers/activation_pot_inferable_quantizer.py
> +    class ActivationPOTInferableQuantizer(BasePOTInferableQuantizer):
Why unique quantizer for PO2? We implemented it as Symmetric with flag. You can see it look pretty much like symmetric_inferable_quantizer

2023-01-05 12:53 UTC, eladc-git commented on model_compression_toolkit/qunatizers_infrastructure/keras/inferable_quantizers/base_pot_inferable_quantizer.py
> +class BasePOTInferableQuantizer(BaseKerasInferableQuantizer):
same here. lack of reuse code of symmetric.

2023-01-05 12:53 UTC, eladc-git commented on tests/keras_tests/feature_networks_tests/feature_networks/scale_equalization_test.py
> +        print('*****************')
How this related to this PR?

2023-01-05 12:53 UTC, eladc-git commented on model_compression_toolkit/qunatizers_infrastructure/keras/inferable_quantizers/base_pot_inferable_quantizer.py
> +        self.max_range = threshold - delta
Where is get config function?

2023-01-05 12:53 UTC, eladc-git commented on model_compression_toolkit/qunatizers_infrastructure/keras/inferable_quantizers/base_keras_inferable_quantizer.py
> +        """
Where is get config function as abstract?

2023-01-05 12:53 UTC, eladc-git commented on model_compression_toolkit/qunatizers_infrastructure/common/base_inferable_quantizer.py
> +class BaseInferableQuantizer:
I think this name should be BaseQuantizer without the infereable, and BaseTrainableQuantizer and BaseInferableQuantizer should inherit from it.

2023-01-05 18:58 UTC, reuvenperetz commented
Two things:
1. There is a fix for a non-related issue (in scale equalization). It will be merged in a different PR (this is just for the tests to pass).
2. The design hierarchies are supposed to keep it simple (this is why for example, I choose not to inherit quantizers from different quantization methods one from another (pot -> symmetric -> uniform). If you find it problematic, we can talk about it.

2023-01-08 10:26 UTC, eladc-git approved these changes

2023-01-08 10:27 UTC, merged