Qi readme
sony/model_optimization pull request #546
Opened 2023-01-25 09:16 UTC by Idan-BenAmi

2023-01-29 07:50 UTC, elad-c requested changes

2023-01-29 07:50 UTC, elad-c commented on model_compression_toolkit/quantizers_infrastructure/README.md
> +# Quantizers Infrastructure (QI)
Need license?

2023-01-29 07:50 UTC, elad-c commented on model_compression_toolkit/quantizers_infrastructure/README.md
> +Quantizer instance implements the quantization function: conversion of floating point values to quantized values represented in floating point (fake-quantization).
1. A\The
2. The quantizer quantizes an input tensor that might be float (weights) or quantized (most activations)

2023-01-29 07:50 UTC, elad-c commented on model_compression_toolkit/quantizers_infrastructure/README.md
> +Quantizer instance should be defined per layer, separately for weights quantization and activations quantization.
A\The

2023-01-29 07:50 UTC, elad-c commented on model_compression_toolkit/quantizers_infrastructure/README.md
> +`BaseInferableQuantizer` - A type of quantizer that uses for emulating inference-time quantization
is used for

2023-01-29 07:50 UTC, elad-c commented on model_compression_toolkit/quantizers_infrastructure/README.md
> +`BaseTrainableQuantizer` - A type of quantizer that uses for quantization optimization during training. This type of quantizer contains learnable parameters
is used for

2023-01-29 07:50 UTC, elad-c commented on model_compression_toolkit/quantizers_infrastructure/README.md
> +# generate a signed 8-bits symmetric quantizer for numbers in the interval [-2,2)
interval [-2, 2-LSB]

2023-01-29 07:50 UTC, elad-c commented on model_compression_toolkit/quantizers_infrastructure/README.md
> +`NodeQuantizationDispatcher` instance contains a list of relevant quantizers for node (layer) in the model:
The NodeQuantizationDispatcher`
a node

2023-01-29 07:50 UTC, elad-c commented on model_compression_toolkit/quantizers_infrastructure/README.md
> +activation quantizer per layer's output
(Add bullets)

_The_ weights quantizer _quantizes a tensor_ per attribute_\(maybe per channel?)_ (kernel, bias, ...)
_The_ activation quantizer _quantizes a tensor_ per layer's output

2023-01-29 07:50 UTC, elad-c commented on model_compression_toolkit/quantizers_infrastructure/README.md
> +# generate node dispatcher with the above weights quantizer
a node

2023-01-29 07:50 UTC, elad-c commented on model_compression_toolkit/quantizers_infrastructure/README.md
> +dispatcher = qi.KerasNodeQuantizationDispatcher(w_quantizer)
The dispatcher is called with a dict: {name: quantizer}
also, use the kwarg when calling a class: qi.KerasNodeQuantizationDispatcher(weight_quantizers=your dict)

2023-01-29 07:50 UTC, elad-c commented on model_compression_toolkit/quantizers_infrastructure/README.md
> +A quantization wrapper instance is used as a layer's replacement which emulates the layer's operation only with quantization.
remove "only"

2023-01-29 07:50 UTC, elad-c commented on model_compression_toolkit/quantizers_infrastructure/README.md
> +`KerasQuantizationWrapper` - used to wrap Keras layer
"to wrap" => for warpping a

2023-01-29 07:50 UTC, elad-c commented on model_compression_toolkit/quantizers_infrastructure/README.md
> +`PytorchQuantizationWrapper` - used to wrap torch nn module
a torch

2023-01-29 07:50 UTC, elad-c commented on model_compression_toolkit/quantizers_infrastructure/README.md
> +`TrainableQuantizerWeightsConfig` - contains the configuration of weight quantization for the trainable quantizer.
the trainable quantizer => a trainable quantizer

2023-01-29 07:50 UTC, elad-c commented on model_compression_toolkit/quantizers_infrastructure/README.md
> +`TrainableQuantizerActivationConfig` - contains the configuration of activation quantization for trainable quantizer
the trainable quantizer => a trainable quantizer

2023-01-29 07:50 UTC, elad-c commented on model_compression_toolkit/quantizers_infrastructure/README.md
> +# generate example configurations for trainable quantizer
for a

2023-01-29 07:50 UTC, elad-c commented on model_compression_toolkit/quantizers_infrastructure/README.md
> +q_config = qi.TrainableQuantizerWeightsConfig(weights_quantization_method=QuantizationMethod.POWER_OF_TWO,
import for QuantizationMethod

2023-01-29 07:50 UTC, elad-c commented on model_compression_toolkit/quantizers_infrastructure/README.md
> +qi.KerasQuantizationWrapper(layer=model.layers[1], dispatcher)
Don't we want the "clone" code for actually replacing the layer with the wrapped layer?

2023-01-30 18:40 UTC, elad-c approved these changes
few minor comments

2023-01-30 18:40 UTC, elad-c commented on model_compression_toolkit/quantizers_infrastructure/README.md
> +To create quantization abstraction in a model,
why start a new line after the comment?

2023-01-30 18:40 UTC, elad-c commented on model_compression_toolkit/quantizers_infrastructure/README.md
> +"Inferable Quantizer", is used for emulating inference-time quantization, and "Trainable Quantizer", contains learnable quantization parameters that can be optimized during training.
The "Inferable Quantizer" is used

2023-01-31 07:54 UTC, reuvenperetz approved these changes

2023-01-31 09:36 UTC, merged