Automatic mapping from quantization method to quantizer
sony/model_optimization pull request #566
Opened 2023-02-05 10:36 UTC by ofirgo

Replacing the manual mapping from quantization target and method to quantizer in quantization infrastructure using a new `@mark_quantizer` decorator.
The main changes include:
- Implementing the `@mark_quantizer` decorator, which should be used to decorate all quantizers class (currently, QAT and Inferable quantizers). It defines static properties that allow to classify the quantizer - quantization methodm quantization target and quantizer type.
- Adding a middle layer for QAT trainable quantizers - BaseKerasQATTrainableQuantizer and BasePytorchQATTrainableQuantizer.
- Removing the global mapping dictionaries from node_to_quantizer and quantizer_builder and replacing them with an automatic selection of the appropriate quantizer.
- Removing QuantizationMethod import from QI.
- Updating Readmes for adding a new quantizer.
- Other minor cosmetic changes.

2023-02-05 12:07 UTC, elad-c requested changes

2023-02-05 12:07 UTC, elad-c commented on model_compression_toolkit/quantizers_infrastructure/pytorch/README.md
> +The [`mark_quantizer`](https://github.com/ofirgo/model_optimization/blob/301a6c024828075bf1e6429de6a2750f26732170/model_compression_toolkit/quantizers_infrastructure/common/base_inferable_quantizer.p
this is your fork
relative links will solve this

2023-02-05 12:07 UTC, elad-c commented on model_compression_toolkit/quantizers_infrastructure/pytorch/base_pytorch_quantizer.py
> +            super().__init__(quantization_config)
BasePytorchTrainableQuantizer

2023-02-05 13:02 UTC, ofirgo commented on model_compression_toolkit/qat/pytorch/quantizer/quantization_builder.py
> +def _get_quantizer_class(quant_target: QuantizationTarget,
It's only common in qat and in qi (for each of them there still needs to be implemented a separate _get_quantizer_class).
I'll move this to common in each of the packages, but it wouldn't eliminate all the duplication.

2023-02-05 13:20 UTC, Idan-BenAmi commented on model_compression_toolkit/exporter/model_wrapper/keras/builder/node_to_quantizer.py
> +            use the quantizer for.
maybe you can add for simplicity: weights or activation

2023-02-05 13:59 UTC, ofirgo commented on model_compression_toolkit/quantizers_infrastructure/common/base_trainable_quantizer.py
> +            # TODO: add test that defines a new quantizer without the decorator and check for the exception.
Added.

2023-02-05 15:46 UTC, Idan-BenAmi commented on model_compression_toolkit/quantizers_infrastructure/pytorch/README.md
> +[`BasePytorchTrainableQuantizer`](./base_pytorch_quantizer.py) constitutes a base class for trainable quantizers of specific of specific tasks - currently, [`BasePytorchQATTrainableQuantizer`](../../
trainable quantizers of specific **of specific** tasks

2023-02-05 20:14 UTC, haihabi commented on model_compression_toolkit/exporter/model_wrapper/common/__init__.py
> +# Copyright 2022 Sony Semiconductor Israel, Inc. All rights reserved.
2023

2023-02-06 07:51 UTC, ofirgo commented on model_compression_toolkit/exporter/model_wrapper/pytorch/builder/node_to_quantizer.py
> +def _get_quantizer_class(quant_target: QuantizationTarget,
Yes I moved it to a common location

2023-02-06 10:19 UTC, Idan-BenAmi approved these changes

2023-02-06 12:25 UTC, merged