Regularization API for trainable quantizers
sony/model_optimization pull request #604
Opened 2023-03-14 15:27 UTC by ofirgo

Extracting the regularization from the quantizer to a higher level.
Now, each trainable quantizer should define its regularization function (if it needs one) near the quantizer implementation, such that the function gets the entire wrapped model and computes the regularization value.
Necessary modifications were applied also to GPTQ configuration and tests.

2023-03-15 14:38 UTC, elad-c requested changes

2023-03-15 14:38 UTC, elad-c commented on model_compression_toolkit/gptq/common/gptq_config.py
> +            entropy_reg (float): A floating point number that defines the gumbel regularization factor.
maybe change to regularization_factor. relevant for all quantizers, not only gumbel

2023-03-15 14:38 UTC, elad-c commented on model_compression_toolkit/gptq/keras/quantizer/soft_rounding/soft_quantizer_reg.py
> +    Args:
missing args

2023-03-15 14:38 UTC, elad-c commented on model_compression_toolkit/gptq/keras/quantizer/soft_rounding/soft_quantizer_reg.py
> +def soft_quantizer_regularization(model: Model, entropy_reg: float, n_batches: int, n_epochs: int) -> float:
can get only total_gragient_steps (n_batches*n_epochs)

2023-03-15 14:38 UTC, elad-c commented on model_compression_toolkit/gptq/keras/quantizer/soft_rounding/soft_quantizer_reg.py
> +    init_decay = MAX_ITERATIONS_DEFAULT if n_batches is None else n_epochs * n_batches
can change to var name (total_grad...)

2023-03-15 14:38 UTC, elad-c commented on model_compression_toolkit/gptq/pytorch/quantizer/regularization_factory.py
> +        n_epochs = N_EPOCHS if not type(gptq_config) == GradientPTQConfigV2 else gptq_config.n_epochs
generate GPTQconfigV2 with from_v1. with num_batches as the "n_ptq_iter" argument.
remove N_EPOCHS from code
n_epochs = gptqv2.n_epochs

2023-03-15 14:38 UTC, elad-c commented on model_compression_toolkit/gptq/pytorch/quantizer/soft_rounding/soft_quantizer_reg.py
> +def soft_quantizer_regularization(model: nn.Module, entropy_reg: float, n_batches: int, n_epochs: int) -> float:
dame as keras comments

2023-03-15 14:55 UTC, ofirgo commented on model_compression_toolkit/gptq/common/gptq_training.py
> -            self.count_num_batches_for_training(representative_data_gen)
Remove representative_dataset argument from function (it is not used)

2023-03-19 13:54 UTC, elad-c approved these changes

2023-03-19 13:56 UTC, merged