Fix bug with parameters learning in GPTQ soft quantizers
sony/model_optimization pull request #619
Opened 2023-03-22 11:21 UTC by ofirgo

Fixing two issues:
* In both Pytorch and Keras Soft quantizers - parameters learning wasn't applied for per-tensor quantization.
* In Keras Soft quantizer - per-tensor quantization did not use the soft targets.

2023-03-23 13:16 UTC, elad-c requested changes

2023-03-23 13:16 UTC, elad-c commented on model_compression_toolkit/gptq/keras/quantizer/soft_rounding/symmetric_soft_quantizer.py
> +                                                         auxvar_tensor=self.get_quantizer_variable(AUXVAR),
don't you need to pass aux_var?

2023-03-23 13:38 UTC, ofirgo commented on model_compression_toolkit/gptq/keras/quantizer/soft_rounding/symmetric_soft_quantizer.py
> +                                                         auxvar_tensor=self.get_quantizer_variable(AUXVAR),
You are right, that was the whole point

2023-03-23 14:13 UTC, elad-c approved these changes

2023-03-28 13:35 UTC, elad-c approved these changes

2023-03-28 13:35 UTC, elad-c commented on tests/keras_tests/function_tests/test_gptq_soft_quantizer.py
> +        def _generate_input():
no need for a function

2023-03-28 13:35 UTC, elad-c commented on tests/keras_tests/function_tests/test_gptq_soft_quantizer.py
> +        def _generate_input():
same

2023-03-28 14:06 UTC, merged