Remove deepcopy
sony/model_optimization pull request #625
Opened 2023-04-09 09:37 UTC by elad-c

2023-04-10 06:29 UTC, ofirgo requested changes

2023-04-10 06:29 UTC, ofirgo commented on model_compression_toolkit/core/common/substitutions/apply_substitutions.py
> +def substitute(graph: common.Graph,
This one seems a bit dangerous. How can we verify that there in no one substitution that is counting on the fact that the graph is being copied? I'm not sure that our tests can ensure this.

2023-04-10 06:29 UTC, ofirgo commented on model_compression_toolkit/core/runner.py
> +    transformed_graph = set_quantization_configuration_to_graph(graph_with_qcs=transformed_graph,
the graph that you are passing here doesn't have QCs, so the name of the argument is confusing.

2023-04-16 08:32 UTC, ofirgo approved these changes

2023-04-16 10:24 UTC, haihabi commented
Please link to the issue

2023-04-17 15:05 UTC, ofirgo commented on model_compression_toolkit/core/keras/keras_implementation.py
> +from copy import deepcopy
Is this import necessary?

2023-04-17 15:07 UTC, ofirgo approved these changes

2023-04-18 08:18 UTC, merged