Add ActivationQuantizationHolder and use it during GPTQ
sony/model_optimization pull request #655
Opened 2023-05-08 18:06 UTC by reuvenperetz

Add ActivationQuantizationHolder layer to hold an activation quantizer and quantize during inference.
Update Keras model builder to use it as quantization layers if it is passed (instead of
KerasQuantizeWrapper that was used for both weights and activations).
For now, only GPTQ uses it by passing it to the model builder - thus, GPTQ models wrap layers
with weight quantizers and quantize activations using ActivationQuantizationHolder layers.

2023-05-09 04:30 UTC, haihabi commented on model_compression_toolkit/qat/keras/quantization_facade.py
> +    def qat_wrapper(n: common.BaseNode,
Why do we need to change QAT?

2023-05-09 13:49 UTC, ofirgo requested changes

2023-05-09 13:49 UTC, ofirgo commented on model_compression_toolkit/qat/keras/quantization_facade.py
> +            if wrap_with_activation_quantizers:
Update this according to what you decide regarding the terminology of "wrapper"/"holder".

2023-05-09 13:49 UTC, ofirgo commented on tests/keras_tests/feature_networks_tests/feature_networks/gptq/gptq_test.py
> +    x = layers.Conv2D(64, 4)(inputs)
add function test to test graph builder

2023-05-10 16:04 UTC, reuvenperetz commented on model_compression_toolkit/core/keras/back2framework/keras_model_builder.py
> +                                        wrap_with_activation_quantizers=self.use_activation_quantizers_in_wrapper)
So it'll be possible to do it in phases in different PRs (next PRs: QAT, Exporter, etc.)

2023-05-11 11:56 UTC, merged