fix_pytorch_exporter_validae_layer
sony/model_optimization pull request #679
Opened 2023-06-01 11:23 UTC by eladc-git

2023-06-01 11:36 UTC, reuvenperetz requested changes

2023-06-01 11:36 UTC, reuvenperetz commented on model_compression_toolkit/exporter/model_wrapper/pytorch/validate_layer.py
> +            return isinstance(layer.activation_holder_quantizer, BasePyTorchInferableQuantizer)
Add check that every layer must be an nn.module.
Maybe it's better to raise an error with an informative error message in cases it's not a valid layer?

2023-06-04 12:49 UTC, reuvenperetz approved these changes

2023-06-04 12:49 UTC, reuvenperetz commented on model_compression_toolkit/exporter/model_wrapper/pytorch/validate_layer.py
> +                    f'KerasQuantizationWrapper must have a weights_quantizers but has a '
It's not a KerasQuantizationWrapper

2023-06-04 12:49 UTC, reuvenperetz commented on model_compression_toolkit/exporter/model_wrapper/pytorch/validate_layer.py
> +                Logger.error(f'KerasQuantizationWrapper must have at least one weight quantizer, but found {len(layer.weights_quantizers)} quantizers.'
It's not a KerasQuantizationWrapper

2023-06-04 12:49 UTC, reuvenperetz commented on model_compression_toolkit/exporter/model_wrapper/pytorch/validate_layer.py
> +            Logger.error(f'Exportable layer must be a Pytorch layer, but layer {layer.name} is of type {type(layer)}') # pragma: no cover
Exportable layer must be a Pytorch *layer* -> Exportable layer must be a Pytorch *nn.Module*

2023-06-04 12:49 UTC, reuvenperetz approved these changes

2023-06-04 12:52 UTC, eladc-git commented on model_compression_toolkit/exporter/model_wrapper/pytorch/validate_layer.py
> +                Logger.error(f'KerasQuantizationWrapper must have at least one weight quantizer, but found {len(layer.weights_quantizers)} quantizers.'
opsssss

2023-06-04 12:54 UTC, merged