Add BatchNorm forward folding
sony/model_optimization pull request #698
Opened 2023-06-13 16:53 UTC by elad-c

Also bug fixes:
 * PyTorch BN folding after ConvTranspose2d
 * PyTorch scale equalization test

2023-06-22 06:29 UTC, eladc-git requested changes

2023-06-22 06:29 UTC, eladc-git commented on model_compression_toolkit/core/common/substitutions/batchnorm_folding.py
> +        conv_bn.weights = weights_dict
it should be "bn_conv" in the variables and in the names

2023-06-22 06:29 UTC, eladc-git commented on model_compression_toolkit/core/keras/graph_substitutions/substitutions/batchnorm_folding.py
> +def batchnorm_forward_folding_node_matchers():
return type

2023-06-22 06:29 UTC, eladc-git commented on tests/pytorch_tests/model_tests/feature_models/bn_folding_test.py
> +class BNForwardFoldingNet(torch.nn.Module):
I would add a test with 2 bn, something like: **bn->conv->bn->relu** to check that it converted to **conv->relu**

2023-06-22 09:29 UTC, lior-dikstein commented on model_compression_toolkit/core/keras/graph_substitutions/substitutions/batchnorm_folding.py
> +    """
Shouldn't the name of the function be "get_kernel_fw_shape_fn"?

2023-06-22 09:38 UTC, lior-dikstein commented on model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/batchnorm_folding.py
> +def get_kernel_hw_fn(kernel: np.ndarray):
same comment about the name as the one in Keras

2023-06-22 09:42 UTC, lior-dikstein commented on tests/keras_tests/feature_networks_tests/feature_networks/bn_folding_test.py
> +    def __init__(self, unit_test, test_layer, conversion_applied):
Please add a description of what you are testing

2023-06-22 09:43 UTC, lior-dikstein commented on tests/keras_tests/feature_networks_tests/feature_networks/bn_folding_test.py
> +        self.test_layer = test_layer
what about testing cases where the BN shouldn't be folded?

2023-06-22 09:45 UTC, lior-dikstein commented on tests/pytorch_tests/model_tests/feature_models/bn_folding_test.py
> +
Please also add descriptions of what you are testing in Pytorch

2023-06-22 09:47 UTC, lior-dikstein commented on tests/pytorch_tests/model_tests/test_feature_models_runner.py
> +        BNFoldingNetTest(self, nn.Conv2d(3, 3, kernel_size=3, groups=3)).run_test()
Can you add comments on the Conv types - for instance, groups=3 is depthwise

2023-06-25 04:48 UTC, eladc-git approved these changes

2023-06-25 05:56 UTC, merged