Data gen tutorial and output loss
sony/model_optimization pull request #805
Opened 2023-09-13 07:39 UTC by lior-dikstein

2023-09-13 07:51 UTC, lapid92 commented on model_compression_toolkit/data_generation/pytorch/model_info_exctractors.py
> +                    if isinstance(module, Linear) or isinstance(module, Conv2d):
Consider defining Linear/Conv2d as an input to the function. So user can add conv3d for example

2023-09-13 07:52 UTC, lapid92 commented on model_compression_toolkit/data_generation/pytorch/optimization_functions/output_loss_functions.py
> +    Calculate the minimum-maximum difference of output images.
Update func doc

2023-09-13 07:59 UTC, lapid92 approved these changes

2023-09-13 10:45 UTC, elad-c requested changes

2023-09-13 10:45 UTC, elad-c commented on model_compression_toolkit/data_generation/README.md
> +data_gen_config = mct.get_tensorflow_data_generation_config(n_iter=500,  # Number of iterations
why not move the arguments a line below, same as above?

2023-09-13 10:45 UTC, elad-c commented on model_compression_toolkit/data_generation/pytorch/constants.py
> +import torch
why do you import torch?

2023-09-13 10:45 UTC, elad-c commented on model_compression_toolkit/data_generation/pytorch/model_info_exctractors.py
> +        # This code finds the output layers of the model and adds hooks to the input activation of
maybe put all this code in a function for readability?

2023-09-13 10:45 UTC, elad-c commented on model_compression_toolkit/data_generation/pytorch/optimization_functions/output_loss_functions.py
> +        weights_norm = torch.linalg.norm(output_weight, dim=1)
Add comment that explains the calculation and it's objective\incentive

2023-09-13 10:45 UTC, elad-c commented on model_compression_toolkit/data_generation/pytorch/pytorch_data_generation.py
> +		# Get Data Generation functions and classes
align comment

2023-09-13 10:47 UTC, ofirgo approved these changes
None of the requested changes is mandatory so I approved, but consider them

2023-09-13 10:47 UTC, ofirgo commented on tutorials/notebooks/example_pytorch_data_generation.ipynb
I don't know why I can't put a comment on specific lines in this file, so I summarize them here:
- In few sentences there is a missing period at the end.
- "Data**-**free" vs. "Data Free" (consistency).
- In the block for setting MCT configuration there is a comment regarding z score, but the code doesn't reference any z score related settings, so maybe remove the comment.
- Remove the hardcoded path to imagenet_validation folder (I'm guessing it was left there by mistake).

2023-09-13 10:47 UTC, ofirgo commented on model_compression_toolkit/data_generation/pytorch/constants.py
> +import torch
why?

2023-09-13 10:47 UTC, ofirgo commented on model_compression_toolkit/data_generation/pytorch/model_info_exctractors.py
> +        for node in fx_model.graph.nodes:
This code can be replaced with a one-liner to create the list, consider it if you like

2023-09-13 10:47 UTC, ofirgo commented on model_compression_toolkit/data_generation/pytorch/pytorch_data_generation.py
> +		# Get Data Generation functions and classes
extra tab here?

2023-09-14 08:02 UTC, elad-c approved these changes

2023-09-14 09:58 UTC, merged