Add yolov8n tutorial with integrated post processing
sony/model_optimization pull request #855
Opened 2023-11-08 12:26 UTC by Idan-BenAmi

## Pull Request Description:
In this pull request I added tutorial of yolov8n object detection model with integrated post processing.

## Checklist before requesting a review:
- [ ] I set the appropriate labels on the pull request.
- [ ] I have added/updated the release note draft (if necessary).
- [ ] I have updated the documentation to reflect my changes (if necessary).
- [ ] All function and files are well documented. 
- [ ] All function and classes have type hints.
- [ ] There is a licenses in all file.
- [ ] The function and variable names are informative. 
- [ ] I have checked for code duplications.
- [ ] I have added new unittest (if necessary).

2023-11-09 14:29 UTC, elad-c requested changes

2023-11-09 14:29 UTC, elad-c commented on tutorials/notebooks/example_keras_yolov8n.ipynb
> +    "quant_model, _ = mct.ptq.keras_post_training_quantization_experimental(model,\n",
if this model should run on the IMX500, define the explicit TPC:
```
# Set IMX500-v1 TPC
tpc = mct.get_target_platform_capabilities("tensorflow", 'imx500', target_platform_version='v1')
```

2023-11-09 14:29 UTC, elad-c commented on tutorials/notebooks/example_keras_yolov8n.ipynb
> +    "Lastly, we can evaluate the performance of the quantized model. There is a slight decrease in performance that can be further mitigated by either expanding the representative dataset or employin
still called GPTQ in the MCT :)

2023-11-09 14:29 UTC, elad-c commented on tutorials/resources/nanodet/__init__.py
Add license

2023-11-09 14:29 UTC, elad-c commented on tutorials/resources/yolov8/__init__.py
license

2023-11-09 14:29 UTC, elad-c commented on tutorials/resources/yolov8/yolov8_keras.py
> +# Copyright 2023 Sony Semiconductor Israel, Inc. All rights reserved.
if this code was copied from ultralytics and modified, then you need to change the license. Check out the license in

> https://github.com/sony/model_optimization/blob/main/tutorials/resources/efficientdet/effdet_keras.py

2023-11-09 14:29 UTC, elad-c commented on tutorials/resources/yolov8/yolov8_keras.py
> +    model.save('/data/projects/swat/network_database/Tensorflow2/float/yolov8n/temp.h5')
remove this

2023-11-09 14:29 UTC, elad-c commented on tutorials/resources/yolov8/yolov8_keras.py
> +if __name__ == '__main__':
remove this

2023-11-09 14:29 UTC, elad-c commented on tutorials/resources/yolov8/yolov8n.yaml
> +# Copyright 2023 Sony Semiconductor Israel, Inc. All rights reserved.
Same comment about license. if you didn't change the file at all, maybe download it online

2023-11-12 07:54 UTC, Idan-BenAmi commented on tutorials/notebooks/example_keras_yolov8n.ipynb
> +    "PRETRAINED_WEIGHTS_FILE = '/content/yolov8n.pt'\n",
I keep it to emphasize this path could be defined by the user (depends if he uses collab or his local disk)

2023-11-12 07:56 UTC, Idan-BenAmi commented on tutorials/notebooks/example_keras_yolov8n.ipynb
> +    "Please ensure that the dataset path has been set correctly before running this code cell."
Again, just to emphasize this could be modified if needed.

2023-11-12 13:03 UTC, elad-c approved these changes
checkout the comments

2023-11-12 13:03 UTC, elad-c commented on tutorials/notebooks/example_keras_nanodet_plus.ipynb
> +    "    def representative_dataset() -> Iterator[List]:\n",
Need function doc:

>  
       """
        Creates a representative dataset generator from a PyTorch data loader, The generator yields numpy
        arrays of batches of shape: [Batch, H, W ,C]
        Returns:
            A representative dataset generator
        """

2023-11-12 14:33 UTC, merged