Add Op2d->add_const collapse substitution
sony/model_optimization pull request #878
Opened 2023-12-04 13:27 UTC by elad-c

## Pull Request Description:
Add a substitution for collapsing Op2d->add-const into the Op2d node
Op2d: Conv2D, DW-Conv2D, Conv2DTranspose or Dense

## Checklist before requesting a review:
- [x] I set the appropriate labels on the pull request.
- [x] I have added/updated the release note draft (if necessary).
- [x] I have updated the documentation to reflect my changes (if necessary).
- [x] All function and files are well documented. 
- [x] All function and classes have type hints.
- [x] There is a licenses in all file.
- [x] The function and variable names are informative. 
- [x] I have checked for code duplications.
- [x] I have added new unittest (if necessary).

2023-12-04 15:20 UTC, eladc-git commented
General question: why implementation is per framework? if I understand it correctly, the substitution is only adding the const to Op2D_bias so it can be done on graph (common). I didn't see the "per framework" factor here.

2023-12-05 05:35 UTC, eladc-git requested changes

2023-12-05 05:35 UTC, eladc-git commented on model_compression_toolkit/core/common/substitutions/linear_collapsing_substitution.py
> +    if linear_collapsing_substitution is None:
what is this TODO? and why pytorch is mentioned in common?

2023-12-05 05:35 UTC, eladc-git commented on model_compression_toolkit/core/keras/graph_substitutions/substitutions/linear_collapsing.py
> +        Logger.error(f'Unable to read constant from add node: {add_node.name}')
add no cover

2023-12-05 05:35 UTC, eladc-git commented on model_compression_toolkit/core/keras/graph_substitutions/substitutions/linear_collapsing.py
> +        Logger.error(f'Unable to convert constant to numpy array: {add_node.name}')
no cover

2023-12-05 05:35 UTC, eladc-git commented on model_compression_toolkit/core/pytorch/pytorch_implementation.py
> +        return None
what about pytorch implementation?

2023-12-05 05:35 UTC, eladc-git commented on tests/keras_tests/feature_networks_tests/feature_networks/linear_collapsing_test.py
> +            if type(layer) in [layers.Conv2D, layers.DepthwiseConv2D, layers.Conv2DTranspose, layers.Dense]:
you can save the const in the init function and then check here if it equals to the bias (when bias is none).

2023-12-05 09:08 UTC, eladc-git approved these changes

2023-12-05 09:15 UTC, reuvenperetz approved these changes

2023-12-05 09:15 UTC, reuvenperetz commented on model_compression_toolkit/core/common/substitutions/linear_collapsing.py
> +        op2d_collapsed_name = first_node.name + '_collapsed'
I think the name manipulation is meaningless and may add confusion... what do you think?

2023-12-05 14:01 UTC, merged