Add BatchNorm information collection
sony/model_optimization pull request #99
Opened 2022-02-21 08:37 UTC by lapid92

2022-02-22 06:51 UTC, reuvenperetz commented on model_compression_toolkit/common/substitutions/batchnorm_info_collection.py
> +        """
Fix args names (moving mean -> moving_mean, etc.)

2022-02-27 07:52 UTC, haihabi commented on model_compression_toolkit/common/graph/graph_matchers.py
> +class EveryNodeOperationMatcher(node_matcher.BaseNodeMatcher):
Remove this class and use Node Matcher instade.

2022-02-27 07:56 UTC, haihabi commented on model_compression_toolkit/common/post_training_quantization.py
>                                                        fw_info=fw_info)
Why does the batch-normalization information is not initialized in get_node_prior_info?

2022-03-02 14:34 UTC, reuvenperetz requested changes

2022-03-02 14:34 UTC, reuvenperetz commented on model_compression_toolkit/common/post_training_quantization.py
> +    graph = substitute(graph, fw_impl.get_substitutions_prepare_graph())
I wouldn't remove the logger after the prepare part...

2022-03-02 14:34 UTC, reuvenperetz commented on tests/keras_tests/function_tests/test_bn_info_collection.py
> +#
Please use license with 2022 for new files

2022-03-02 14:34 UTC, reuvenperetz commented on model_compression_toolkit/keras/keras_node_prior_info.py
> +
If we don't have them use 0,1

2022-03-03 09:15 UTC, merged